apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-backend
spec:
  selector:
    matchLabels:
      app: aplicacao-backend
  template:
    metadata:
      labels:
        app: aplicacao-backend
    spec:
      containers:
        - name: aplicacao-backend
          image: bdiogoandre/backend-teste-docker:v7
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
          - containerPort: 80
      dnsPolicy: Default
