apiVersion: v1
kind: Service
metadata:
  name: aplicacao-backend
  labels:
    app: aplicacao-backend
spec:
  type: LoadBalancer
  selector:
    app: aplicacao-backend
  ports:
  - port: 80
    targetPort: 80
